import AnimalAttachmentModel from "./AnimalAttachmentModel";
import AnimalImageModel from "./AnimalImageModel";
import BreedModel from "./BreedModel";
import EntityTemporaryHome from "./EntityTemporaryHome";
import MedicineAnimal from "./MedicineAnimal";
import TreatmentModel from "./TreatmentModel";
import UserModel from "./UserModel";

export default class AnimalModel {
    id: number | null = null;
    name: string = '';
    species: number | null = null;
    age: number = 1;
    collectionDate: string | undefined;
    collectionPlace: string = '';
    size: number = 0;
    gender: number = 0;
    weight: number | undefined;
    idColor: number | undefined;
    idBreed: number | undefined;
    breed: BreedModel | undefined;
    idSituation: number = 0;
    idAdoptionUser: number | undefined;
    deathDate: string | undefined;
    deathDetail: string = '';
    adoptionDate: string | undefined;
    adoptionSolicitationDate: string = '';
    adoptionApprovalDate: string | undefined;
    adoptionUser: UserModel | undefined;
    animalImages: AnimalImageModel[] | undefined = [];
    observation: string = '';
    treatment: TreatmentModel[] = [];
    idTemporaryHome: number | undefined;
    temporaryHome: EntityTemporaryHome | undefined;
    medicineAnimal: MedicineAnimal[] = [];
    images: AnimalImageModel[] = [];
    animalAttachments: AnimalAttachmentModel[] | undefined = [];
    deletedImages: number[] = [];
    deletedAnimalAttachments: number[] = [];
    forwardingDate: string | undefined;
    castrated!: boolean;
    role!: number | undefined;
}